# Generated by Django 5.2.8 on 2025-11-27 08:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет доступ к админке', verbose_name='Статус персонала')),
                ('is_superuser', models.BooleanField(default=False, help_text='Полные права на управление сайтом', verbose_name='Статус суперпользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, help_text='Необязательное поле. Должен быть действительный email.', max_length=254, null=True, verbose_name='Email')),
                ('notification_email', models.EmailField(blank=True, help_text='Email для отправки уведомлений', max_length=254, null=True, verbose_name='Email для уведомлений')),
                ('phone_number', models.CharField(blank=True, help_text='Формат: +1234567890', max_length=20, null=True, validators=[users.models.validate_phone], verbose_name='Номер телефона')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID чата в Telegram для уведомлений', max_length=100, null=True, verbose_name='ID чата Telegram')),
                ('notification_priority', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('sms', 'SMS')], default='telegram', max_length=10, verbose_name='Приоритет уведомлений')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
