# Generated by Django 5.2.8 on 2025-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка'), ('read', 'Прочитано')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram')], db_index=True, max_length=10, verbose_name='Тип уведомления')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Данные провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
